version: '3.9'

services:
  node:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydb

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:80"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: POTLClient
      MONGO_INITDB_ROOT_PASSWORD: 2mzG28gHD94rOd0684sx

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: POTLClient
      ME_CONFIG_MONGODB_ADMINPASSWORD: 2mzG28gHD94rOd0684sx
      ME_CONFIG_MONGODB_URL: mongodb://POTLClient:2mzG28gHD94rOd0684sx@mongo:27017/
    volumes:
      - ./database/mongodb_data:/data/db
