# Use an official Node.js runtime as a parent image
FROM node:20.6.1

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application source code to the working directory
COPY . .

# Expose the port that your Node.js app listens on (e.g., 3000)
EXPOSE 3000

# Define environment variable (optional)
ENV NODE_ENV=development

# Start the Node.js application
CMD ["node", "server.js"]
